"""Project Euler - Problem 29

Consider all integer combinations of a**b for 2 <= a <= 5 and 2 <= b <= 5:

If they are then placed in numerical order, with any repeats removed,
we get the following sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by ab for
2 <= a <= 100 and 2 <= b <= 100?
"""

from itertools import product, tee

def main():
  # Unnecessary, but I don't get to use tee much
  r1, r2 = tee(xrange(2, 101), 2)

  s = set()

  for i in product(r1, r2):
    s.add(i[0]**i[1])

  print len(sorted(s))

if __name__ == '__main__':
  main()
