"""Project Euler - Problem 29

Consider all integer combinations of a**b for 2 <= a <= 5 and 2 <= b <= 5:

If they are then placed in numerical order, with any repeats removed,
we get the following sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by ab for
2 <= a <= 100 and 2 <= b <= 100?
"""


def Euler029():
  return len(set(i**j for i in xrange(2, 101) for j in xrange(2, 101)))

if __name__ == '__main__':
  print Euler029()
